### ISSUE TITLE
SettingManager missing fields from API schema

### ISSUE THREAD

**Issue by sp3nx0r** [snyk-labs/pysnyk#102]
I'd like to be able to modify GHE integration settings (in this case, to enable `pullRequestFailOnlyForIssuesWithFix` and `pullRequestFailOnAnyVulns` on projects where they're certified clean), but the `SettingsManager` doesn't appear to account for the listing of parameters per [API](https://snyk.docs.apiary.io/#reference/projects/project-settings/update-project-settings). I'm not sure if this is GHE specific, but would be useful to get a Manager for these settings as there's only three settings currently defined currently: https://github.com/snyk-labs/pysnyk/blob/fb6b386115df1be3b0ac6dcd5a132ba31375a2ee/snyk/managers.py#L272-L275

**Comment by garethr** [comment]
Hi @sp3nx0r 

Looking to update this to the following, based on https://snyk.docs.apiary.io/#reference/projects/project-settings/update-project-settings

That does include `pullRequestFailOnAnyVulns` but not `pullRequestFailOnlyForIssuesWithFix`, which I don't see? Is that something you'd _like_ to see exposed in the API or have I missed it elsewhere?

```python
settings = [
             "auto_dep_upgrade_enabled",
             "auto_dep_upgrade_ignored_dependencies",
             "auto_dep_upgrade_min_age",
             "auto_dep_upgrade_limit",
             "pull_request_fail_on_any_vulns",
             "pull_request_fail_only_for_high_severity",
             "pull_request_test_enabled",
             "pull_request_assignment",
             "auto_remediation_prs",
         ]
```

**Comment by sp3nx0r** [comment]
Looks like the API documentation is incomplete then. This is what I see when getting all settings via pysnyk:
```
>>> projects[1].id
'ba727368-eda2-44ec-9e45-ce6aea551fcf'
>>> projects[1].settings.all()
{'pullRequestFailOnAnyVulns': False, 'pullRequestFailOnlyForHighSeverity': False, 'pullRequestFailOnlyForIssuesWithFix': True, 'pullRequestInheritance': 'integration', 'pullRequestTestEnabled': True}
```

And that correlates with the checkbox in the UI. We use the "only for issues with fix" logic quite often, so would def like to see that included. Interestingly enough, the other values like `autoDepUpgradeEnabled` aren't present in the API response (checked my GHE imported repos for both Python (shouldn't be supported I believe) and JS (which should be supported). I get a similar response body to the above.

**Comment by garethr** [comment]
Checking with the engineering team, there are some inconsistencies with the docs here that we're fixing. Looks like we should be able to go with:

```diff
settings = [
  "auto_dep_upgrade_enabled",
  "auto_dep_upgrade_ignored_dependencies",
  "auto_dep_upgrade_min_age",
  "auto_dep_upgrade_limit",
  "pull_request_fail_on_any_vulns",
  "pull_request_fail_only_for_high_severity",
  "pull_request_test_enabled",
  "pull_request_assignment",
+  "pull_request_inheritance",
+  "pull_request_fail_only_for_issues_with_fix"
  "auto_remediation_prs",
]
```
