### ISSUE TITLE
Stop using the project issues endpoint

### ISSUE THREAD

**Issue by dantarian** [snyk-labs/pysnyk#124]
The project issues endpoint (`/api/v1/org/<orgId>/project/<projectId>/issues`) has been turned off for most users of the API, and will be removed entirely in the near future.

This means that many users of `issueset` (and maybe other parts of pysnyk) will get errors as the underlying API call will return a 410 response.

`issueset_aggregated` provides an alternative, but ideally `issueset` should be updated to use the currently-supported endpoints described here:

  - https://snyk.docs.apiary.io/#reference/projects/aggregated-project-issues/list-all-aggregated-issues
  - https://snyk.docs.apiary.io/#reference/projects/project-issue-paths/list-all-project-issue-paths

**Comment by carwin** [comment]
Related to this, snyk-labs/snyk-threadfix (which has a dependency on pysnyk) has stopped functioning. 

Stepping through snyk-threadfix issues, it looks like this issues endpoint thing is the ultimate problem. For the users I've talked to so far, API response is that the endpoint no longer exists.

**Comment by garethr** [comment]
Note that pysnyk no longer uses this API, rather using the REST equivalent.
