### ISSUE TITLE
importlib-metadata dependency issue

### ISSUE THREAD

**Issue by benmeyer50** [snyk-labs/pysnyk#128]
When using poetry to install dependencies an error is throw for importlib_metadata. 

Currently the [poetry file](https://github.com/snyk-labs/pysnyk/blob/master/pyproject.toml) calls for `importlib_metadata = "^1.6.1"` but current version is on 4.10.x. This is causing conflicts with other libraries since poetry will only allow the version to be `">=1.6.1" but "<2.0.0"` based on the "^"

Poetry documentation [here](https://python-poetry.org/docs/dependency-specification/#caret-requirements)

**Comment by garethr** [comment]
Thanks for reporting, this should be fixed in the default branch now and will be in the upcoming 0.9.5 release out shortly.
