### ISSUE TITLE
0.9.6 availability

### ISSUE THREAD

**Issue by hs-cames** [snyk-labs/pysnyk#178]
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Description

I wanted to upgrade to the latest version 0.9.6 - it does not seem to be available in standard "pip install" locations

`root@5dc9abe678c7:/app# pip download --no-cache-dir "pysnyk==0.9.6"

ERROR: Could not find a version that satisfies the requirement pysnyk==0.9.6 (from versions: 0.1.2, 0.1.3, 0.2.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5)

ERROR: No matching distribution found for pysnyk==0.9.6`

**Comment by akpay** [comment]
@nathan-roys @garethr @nirfuchs Same issue, Why latest release version [v0.9.6](https://github.com/snyk-labs/pysnyk/releases/tag/v0.9.6) not available for pip install?

https://pypi.org/project/pysnyk/#history

**Comment by garethr** [comment]
Apologies, I'm unsure why the automation didn't automatically push a release for that and we missed this, but more recent issues have been published correctly. Sorry for the slow reply here.
