### ISSUE TITLE
[BUG]: 'NoneType' object has no attribute 'get' ProjectManager._rest_to_v1_response_format

### ISSUE THREAD

**Issue by avipunes-devOcean** [snyk-labs/pysnyk#187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

Following [version 0.9.7 release](https://github.com/snyk-labs/pysnyk/releases/tag/v0.9.7), which contains this [PR](https://github.com/snyk-labs/pysnyk/pull/181/files#diff-529a7eb894217629bcf342ebafea16a0d0a66d692d4d14f43af9b7930a4cf257R145), there is a bug when a project doesn't have "meta.latest_issue_counts` property.
The following [line change](https://github.com/snyk-labs/pysnyk/pull/181/files#diff-529a7eb894217629bcf342ebafea16a0d0a66d692d4d14f43af9b7930a4cf257R145) is missing handling the missing property case.
Therefore the entire call raises an exception, and all projects, even valid ones with the expected property, don't get returned.

To fix this issue, adding default values and two places is necessary.

The following is a fix suggestion:
```python
    def _rest_to_v1_response_format(self, project):
        attributes = project.get("attributes", {})
        settings = attributes.get("settings", {})
        recurring_tests = settings.get("recurring_tests", {})
        issue_counts = project.get("meta", {}).get("latest_issue_counts", {})  # default value for None `latest_issue_counts`

        return {
            "name": attributes.get("name"),
            "id": project.get("id"),
            "created": attributes.get("created"),
            "origin": attributes.get("origin"),
            "type": attributes.get("type"),
            "readOnly": attributes.get("read_only"),
            "testFrequency": recurring_tests.get("frequency"),
            "isMonitored": True if attributes.get("status") == "active" else False,
            "issueCountsBySeverity": {
                "low": issue_counts.get("low", 0), # default value for None `issue_counts` (and for the below as well)
                "medium": issue_counts.get("medium", 0),
                "high": issue_counts.get("high", 0),
                "critical": issue_counts.get("critical"),
            },
            "targetReference": attributes.get("target_reference"),
            "_tags": attributes.get("tags", []),
            "importingUserId": project.get("relationships", {})
            .get("importer", {})
            .get("data", {})
            .get("id"),
            "owningUserId": project.get("relationships", {})
            .get("owner", {})
            .get("data", {})
            .get("id"),
        }
```

The second default value is needed because `Project.issueCountsBySeverity.low`, `Project.issueCountsBySeverity.medium`, and `Project.issueCountsBySeverity.high` are mandatory fields.

### Steps To Reproduce

```python
import snyk
snyk_client = snyk.SnykClient("<put-snyk-api-token-here>")
orgs = snyk_client.organizations.all()
for org in orgs:
    org.projects.all() # exception here
```

**Comment by nathan-roys** [comment]
Released v0.9.14 to address this issue. Thank you for the detailed report & suggested fix.
