### ISSUE TITLE
Error running "pip install pysnyk"

### ISSUE THREAD

**Issue by drychetnik** [snyk-labs/pysnyk#63]
I get the following error when running "pip install pysnyk":
**ERROR: Could not find a version that satisfies the requirement pysnyk (from versions: none)
ERROR: No matching distribution found for pysnyk**

I am somewhat new to Python. Am I doing something wrong?

**Comment by garethr** [comment]
Hi @drychetnik.

Which version of Python are you using? I think the most likely cause of the issue here is you have an old version. `pysnyk` requires at least Python 3.7. https://pypi.org/project/pysnyk/

**Comment by drychetnik** [comment]
Okay, yeah that looks to be the issue. Thanks!
$ python --version
Python 3.6.8
