### ISSUE TITLE
License has no attribute severity

### ISSUE THREAD

**Issue by sp3nx0r** [snyk-labs/pysnyk#75]
Was playing with this trying to understand the API for licenses and this example script was throwing issues that `licenses` has no attribute `severity`. 

https://github.com/snyk-labs/pysnyk/blob/c6763d6dae5845ca8d29096d0b9fb036df5ed9bc/examples/api-demo-4-list-licenses-by-org.py#L29

**Comment by garethr** [comment]
It looks like this should be optional https://github.com/snyk-labs/pysnyk/blob/master/snyk/models.py#L349, based on https://snyk.docs.apiary.io/#reference/licenses/licenses-by-organization/list-all-licenses.
