### ISSUE TITLE
issueset: client is None

### ISSUE THREAD

**Issue by pohly** [snyk-labs/pysnyk#92]
Python: 3.7.3
pysnyk: I installed the API with `pip3 install pysnyk`, which installed 0.4.2.

When running the `examples/api-demo-2-list-issues.py` script, I get an exception:
```
Traceback (most recent call last):
  File "examples/api-demo-2-list-issues.py", line 67, in <module>
    issue_set = project.issueset.all()
  File "/home/pohly/.local/lib/python3.7/site-packages/snyk/managers.py", line 370, in all
    return self.filter()
  File "/home/pohly/.local/lib/python3.7/site-packages/snyk/managers.py", line 387, in filter
    resp = self.client.post(path, post_body)
AttributeError: 'NoneType' object has no attribute 'post'
```

Org ID, project ID and API token are okay. Enabling debug logging shows that communication with the server works and printing `project` confirms that it looks valid (= has data). It's just the `project.issueset` that isn't getting constructed properly.

**Comment by nirfuchs** [comment]
Thank you, @pohly, for reporting this issue.

I've investigated the case, and I'm about to submit a PR that should resolve this issue.
